$(document).ready(function(){
    $('.close1').click(function(){
        $('.search-box').slideUp()
    })
    $('.search').click(function(){
        $('.search-box').slideToggle()
    })
    $('.col-close-icon').click(function(){
        $('.v-menu-outer').css('display','block')
    })
    $('.close2').click(function(){
        $('.v-menu-outer').css('display','none')
    })
    $('.card').hover(function(){
        $('.card').css({'cursor':'pointer',})
    })
    $('.card').click(function(){
        alert('hello  it is work')
    })
})